---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  environments_path: './environments/'
  roles_path: './roles/'
  data_bags_path: "./data_bags" 
  # comment the following two lines for etcd non-proxy setting
  solo_rb:
    environment: "proxy"

platforms:
  - name: centos7
    driver:
      box: "matyunin/centos7"
      customize:
        memory: 2024
        natdnshostresolver1: "on"
        natdnsproxy1: "on"

suites:
  - name: default
    driver:
      network:
      - ["private_network", {ip: "192.168.33.9"}]
    run_list:
      # change the roles for etcd statis and discovery mode
      - role[discovery]
      #- role[static]
      - recipe[fleet-cluster::default]
    attributes: 
      etcd:
        config:
          ipaddress:
            "192.168.33.9"
          name:
            "infra0"
      fleet:
        config:
          net_interface:
            "192.168.33.9"

  - name: peer
    driver:
      network:
      - ["private_network", {ip: "192.168.33.10"}]
    run_list:
      # change the roles for etcd statis and discovery mode
      - role[discovery]
      #- role[static]
      - recipe[fleet-cluster::default]
    attributes: 
      etcd:
        config:
          ipaddress:
            "192.168.33.10"
          name:
            "infra1"
      fleet:
        config:
          net_interface:
            "192.168.33.10"
          metadata: "region=eu-central-1,az=eu-central-1b"

